apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: build-suite-test-secret-overriding
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/susdas/test-images@sha256:b4096a978d35a64deb75597d8e4371cc8d21997b0f76d2847fd294bebbd49848
        name: my-nginx
        resources: {}
status: {}
